version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: fastlane
          command: |
          cd MiniApp
          bundle exec fastlane do_test_app --env -Dev
      # - run: echo "A first hello"
